sudo: required
language: C
services:
- docker
before_install:
- docker info
- docker build -t mariobarbareschi/nova-nre .
- docker run -it -d mariobarbareschi/nova-nre /bin/bash
script:
- docker ps | grep -q mariobarbareschi/nova-nre
